
INSERT INTO _table_ Values("Alderdice", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Deech", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Gale", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Sacks", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Prescott", "Labour", "Lord", "")
INSERT INTO _table_ Values("Royall of Blaisdon", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Collins of Highbury", "Labour", "Lord", "")
INSERT INTO _table_ Values("Sugar", "Labour", "Lord", "")
INSERT INTO _table_ Values("Drayson", "Labour", "Lord", "")
INSERT INTO _table_ Values("Kennedy of Southwark", "Labour", "Lord", "")
INSERT INTO _table_ Values("Lucas", "Conservative", "Lord", "")
INSERT INTO _table_ Values("McConnell of Glenscorrodale", "Labour", "Lord", "")
INSERT INTO _table_ Values("Norton of Louth", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Rennard", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Storey", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Strasburger", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Teverson", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Newby", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Stowell of Beeston", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Deighton", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Sassoon", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Strathclyde", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Anelay of St Johns", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("McNally", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Howe", "Conservative", "Earl", "")
INSERT INTO _table_ Values("Freud", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Hanham", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Astor of Hever", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Hill of Oareford", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Attlee", "Conservative", "Earl", "")
INSERT INTO _table_ Values("De Mauley", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Northover", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Rawlings", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Taylor of Holbeach", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Verma", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Wallace of Saltaire", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Aberdare", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Adams of Craigielea", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Addington", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Adebowale", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Adonis", "Labour", "Lord", "")
INSERT INTO _table_ Values("Afshar", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Ahmad of Wimbledon", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Ahmed", "Labour", "Lord", "")
INSERT INTO _table_ Values("Allan of Hallam", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Allenby of Megiddo", "Crossbench", "Viscount", "")
INSERT INTO _table_ Values("Alli", "Labour", "Lord", "")
INSERT INTO _table_ Values("Alliance", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Alton of Liverpool", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Amos", "Other", "Baroness", "")
INSERT INTO _table_ Values("Anderson of Swansea", "Labour", "Lord", "")
INSERT INTO _table_ Values("Andrews", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Archer of Weston-Super-Mare", "Non-affiliated (current Member)", "Lord", "")
INSERT INTO _table_ Values("Armstrong of Hill Top", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Armstrong of Ilminster", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Arran", "Conservative", "Earl", "")
INSERT INTO _table_ Values("Ashcroft", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Ashdown of Norton-sub-Hamdon", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Ashton of Hyde", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Ashton of Upholland", "Other", "Baroness", "")
INSERT INTO _table_ Values("Astor", "Conservative", "Viscount", "")
INSERT INTO _table_ Values("Attenborough", "Other", "Lord", "")
INSERT INTO _table_ Values("Avebury", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Bach", "Labour", "Lord", "")
INSERT INTO _table_ Values("Baker of Dorking", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Bakewell", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Baldwin of Bewdley", "Crossbench", "Earl", "")
INSERT INTO _table_ Values("Ballyedmond", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Bannside", "Democratic Unionist", "Lord", "")
INSERT INTO _table_ Values("Barber of Tewkesbury", "Other", "Lord", "")
INSERT INTO _table_ Values("Barker", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Barnett", "Labour", "Lord", "")
INSERT INTO _table_ Values("Bassam of Brighton", "Labour", "Lord", "")
INSERT INTO _table_ Values("Bates", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Bath and Wells", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Beecham", "Labour", "Lord", "")
INSERT INTO _table_ Values("Bell", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Benjamin", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Berkeley", "Labour", "Lord", "")
INSERT INTO _table_ Values("Berridge", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Best", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Bew", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Bhatia", "Non-affiliated (current Member)", "Lord", "")
INSERT INTO _table_ Values("Bhattacharyya", "Labour", "Lord", "")
INSERT INTO _table_ Values("Bichard", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Bilimoria", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Billingham", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Bilston", "Labour", "Lord", "")
INSERT INTO _table_ Values("Birmingham", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Birt", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Black of Brentwood", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Black of Crossharbour", "Other", "Lord", "")
INSERT INTO _table_ Values("Blackstone", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Blackwell", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Blair of Boughton", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Blencathra", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Blood", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Blyth of Rowington", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Boateng", "Labour", "Lord", "")
INSERT INTO _table_ Values("Bonham-Carter of Yarnbury", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Boothroyd", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Borrie", "Labour", "Lord", "")
INSERT INTO _table_ Values("Boswell of Aynho", "Non-affiliated (current Member)", "Lord", "")
INSERT INTO _table_ Values("Bottomley of Nettlestone", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Bowness", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Boyce", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Boyd of Duncansby", "Other", "Lord", "")
INSERT INTO _table_ Values("Brabazon of Tara", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Bradley", "Labour", "Lord", "")
INSERT INTO _table_ Values("Bradshaw", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Bragg", "Labour", "Lord", "")
INSERT INTO _table_ Values("Bramall", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Brennan", "Labour", "Lord", "")
INSERT INTO _table_ Values("Bridgeman", "Conservative", "Viscount", "")
INSERT INTO _table_ Values("Bridges", "Other", "Lord", "")
INSERT INTO _table_ Values("Briggs", "Other", "Lord", "")
INSERT INTO _table_ Values("Brinton", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Bristol", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Brittan of Spennithorne", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Broers", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Brooke of Alverthorpe", "Labour", "Lord", "")
INSERT INTO _table_ Values("Brooke of Sutton Mandeville", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Brookeborough", "Crossbench", "Viscount", "")
INSERT INTO _table_ Values("Brookman", "Labour", "Lord", "")
INSERT INTO _table_ Values("Brooks of Tremorfa", "Labour", "Lord", "")
INSERT INTO _table_ Values("Brougham and Vaux", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Brown of Eaton-under-Heywood", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Browne of Belmont", "Democratic Unionist", "Lord", "")
INSERT INTO _table_ Values("Browne of Ladyton", "Labour", "Lord", "")
INSERT INTO _table_ Values("Browne of Madingley", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Browne-Wilkinson", "Other", "Lord", "")
INSERT INTO _table_ Values("Browning", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Burnett", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Burns", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Buscombe", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Butler of Brockwell", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Butler-Sloss", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Byford", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Caithness", "Conservative", "Earl", "")
INSERT INTO _table_ Values("Cameron of Dillington", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Cameron of Lochbroom", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Campbell of Alloway", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Campbell of Loughborough", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Campbell of Surbiton", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Campbell-Savours", "Labour", "Lord", "")
INSERT INTO _table_ Values("Carey of Clifton", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Carlile of Berriew", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Carrington", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Carswell", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Carter of Barnes", "Other", "Lord", "")
INSERT INTO _table_ Values("Carter of Coles", "Labour", "Lord", "")
INSERT INTO _table_ Values("Cathcart", "Conservative", "Earl", "")
INSERT INTO _table_ Values("Cavendish of Furness", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Chadlington", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Chalfont", "Other", "Lord", "")
INSERT INTO _table_ Values("Chalker of Wallasey", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Chandos", "Labour", "Viscount", "")
INSERT INTO _table_ Values("Chester", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Chidgey", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Chitnis", "Other", "Lord", "")
INSERT INTO _table_ Values("Cholmondeley", "Other", "Marquess", "")
INSERT INTO _table_ Values("Chorley", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Christopher", "Labour", "Lord", "")
INSERT INTO _table_ Values("Clancarty", "Crossbench", "Earl", "")
INSERT INTO _table_ Values("Clark of Calton", "Other", "Baroness", "")
INSERT INTO _table_ Values("Clark of Windermere", "Labour", "Lord", "")
INSERT INTO _table_ Values("Clarke of Hampstead", "Labour", "Lord", "")
INSERT INTO _table_ Values("Clarke of Stone-cum-Ebony", "Other", "Lord", "")
INSERT INTO _table_ Values("Clement-Jones", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Clinton-Davis", "Labour", "Lord", "")
INSERT INTO _table_ Values("Cobbold", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Coe", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Cohen of Pimlico", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Collins of Mapesbury", "Non-affiliated (current Member)", "Lord", "")
INSERT INTO _table_ Values("Colville of Culross", "Crossbench", "Viscount", "")
INSERT INTO _table_ Values("Colwyn", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Condon", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Cope of Berkeley", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Cormack", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Corston", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Cotter", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Courtown", "Conservative", "Earl", "")
INSERT INTO _table_ Values("Coussins", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Coventry", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Cox", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Craig of Radley", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Craigavon", "Crossbench", "Viscount", "")
INSERT INTO _table_ Values("Crathorne", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Crawford and Balcarres", "Conservative", "Earl", "")
INSERT INTO _table_ Values("Crawley", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Crickhowell", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Crisp", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Cullen of Whitekirk", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Cumberlege", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Cunningham of Felling", "Labour", "Lord", "")
INSERT INTO _table_ Values("Currie of Marylebone", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Curry of Kirkharle", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Dannatt", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Darzi of Denham", "Labour", "Lord", "")
INSERT INTO _table_ Values("Davidson of Glen Clova", "Labour", "Lord", "")
INSERT INTO _table_ Values("Davies of Abersoch", "Labour", "Lord", "")
INSERT INTO _table_ Values("Davies of Coity", "Labour", "Lord", "")
INSERT INTO _table_ Values("Davies of Oldham", "Labour", "Lord", "")
INSERT INTO _table_ Values("Davies of Stamford", "Labour", "Lord", "")
INSERT INTO _table_ Values("Dean of Thornton-le-Fylde", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Dear", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Deben", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Denham", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Derby", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Desai", "Labour", "Lord", "")
INSERT INTO _table_ Values("Dholakia", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Dixon", "Labour", "Lord", "")
INSERT INTO _table_ Values("Dixon-Smith", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Dobbs", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Donaghy", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Donoughue", "Labour", "Lord", "")
INSERT INTO _table_ Values("Doocey", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Drake", "Labour", "Baroness", "")
INSERT INTO _table_ Values("D'Souza", "Non-affiliated (current Member)", "Baroness", "")
INSERT INTO _table_ Values("Dubs", "Labour", "Lord", "")
INSERT INTO _table_ Values("Dundee", "Conservative", "Earl", "")
INSERT INTO _table_ Values("Dykes", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Eames", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Eaton", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Eatwell", "Labour", "Lord", "")
INSERT INTO _table_ Values("Eccles of Moulton", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Eccles", "Conservative", "Viscount", "")
INSERT INTO _table_ Values("Eden of Winton", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Edmiston", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Elder", "Labour", "Lord", "")
INSERT INTO _table_ Values("Elis-Thomas", "Plaid Cymru", "Lord", "")
INSERT INTO _table_ Values("Elton", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Elystan-Morgan", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Emerton", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Empey", "Ulster Unionist Party", "Lord", "")
INSERT INTO _table_ Values("Erroll", "Crossbench", "Earl", "")
INSERT INTO _table_ Values("Evans of Parkside", "Labour", "Lord", "")
INSERT INTO _table_ Values("Evans of Temple Guiting", "Labour", "Lord", "")
INSERT INTO _table_ Values("Evans of Watford", "Labour", "Lord", "")
INSERT INTO _table_ Values("Exeter", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Ezra", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Falconer of Thoroton", "Labour", "Lord", "")
INSERT INTO _table_ Values("Falkender", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Falkland", "Crossbench", "Viscount", "")
INSERT INTO _table_ Values("Falkner of Margravine", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Farrington of Ribbleton", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Faulkner of Worcester", "Labour", "Lord", "")
INSERT INTO _table_ Values("Faulks", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Fearn", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Feldman of Elstree", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Feldman", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Fellowes of West Stafford", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Fellowes", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Filkin", "Labour", "Lord", "")
INSERT INTO _table_ Values("Fink", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Finlay of Llandaff", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Flather", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Flight", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Fookes", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Ford", "Non-affiliated (current Member)", "Baroness", "")
INSERT INTO _table_ Values("Forsyth of Drumlean", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Foster of Bishop Auckland", "Labour", "Lord", "")
INSERT INTO _table_ Values("Foulkes of Cumnock", "Labour", "Lord", "")
INSERT INTO _table_ Values("Fowler", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Framlingham", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Fraser of Carmyllie", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Freeman", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Freyberg", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Fritchie", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Garden of Frognal", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Gardiner of Kimble", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Gardner of Parkes", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Garel-Jones", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Gavron", "Labour", "Lord", "")
INSERT INTO _table_ Values("Geddes", "Conservative", "Lord", "")
INSERT INTO _table_ Values("German", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Gibson of Market Rasen", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Giddens", "Labour", "Lord", "")
INSERT INTO _table_ Values("Gilbert", "Labour", "Lord", "")
INSERT INTO _table_ Values("Glasgow", "Liberal Democrat", "Earl", "")
INSERT INTO _table_ Values("Glasman", "Labour", "Lord", "")
INSERT INTO _table_ Values("Glenarthur", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Glendonbrook", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Glentoran", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Gloucester", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Goff of Chieveley", "Other", "Lord", "")
INSERT INTO _table_ Values("Gold", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Golding", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Goldsmith", "Labour", "Lord", "")
INSERT INTO _table_ Values("Goodhart", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Goodlad", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Gordon of Strathblane", "Labour", "Lord", "")
INSERT INTO _table_ Values("Goschen", "Conservative", "Viscount", "")
INSERT INTO _table_ Values("Goudie", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Gould of Potternewton", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Grabiner", "Labour", "Lord", "")
INSERT INTO _table_ Values("Grade of Yarmouth", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Graham of Edmonton", "Labour", "Lord", "")
INSERT INTO _table_ Values("Grantchester", "Labour", "Lord", "")
INSERT INTO _table_ Values("Greaves", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Green of Hurstpierpoint", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Greenfield", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Greengross", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Greenway", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Grenfell", "Labour", "Lord", "")
INSERT INTO _table_ Values("Grey-Thompson", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Griffiths of Burry Port", "Labour", "Lord", "")
INSERT INTO _table_ Values("Griffiths of Fforestfach", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Griffiths", "Other", "Lord", "")
INSERT INTO _table_ Values("Grocott", "Labour", "Lord", "")
INSERT INTO _table_ Values("Guildford", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Guthrie of Craigiebank", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Hale of Richmond", "Other", "Baroness", "")
INSERT INTO _table_ Values("Hall of Birkenhead", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Hameed", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Hamilton of Epsom", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Hamwee", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Hannay of Chiswick", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Hanningfield", "Non-affiliated (current Member)", "Lord", "")
INSERT INTO _table_ Values("Hanworth", "Labour", "Viscount", "")
INSERT INTO _table_ Values("Hardie", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Harries of Pentregarth", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Harris of Haringey", "Labour", "Lord", "")
INSERT INTO _table_ Values("Harris of Peckham", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Harris of Richmond", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Harrison", "Labour", "Lord", "")
INSERT INTO _table_ Values("Hart of Chilton", "Labour", "Lord", "")
INSERT INTO _table_ Values("Haskel", "Labour", "Lord", "")
INSERT INTO _table_ Values("Haskins", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Hastings of Scarisbrick", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Hattersley", "Labour", "Lord", "")
INSERT INTO _table_ Values("Haworth", "Labour", "Lord", "")
INSERT INTO _table_ Values("Hayhoe", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Hayman", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Hayter of Kentish Town", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Healey", "Labour", "Lord", "")
INSERT INTO _table_ Values("Healy of Primrose Hill", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Henig", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Henley", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Hennessy of Nympsfield", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Hereford", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Heseltine", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Heyhoe Flint", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Higgins", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Hilton of Eggardon", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Hodgson of Astley Abbotts", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Hoffmann", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Hogg", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Hollick", "Labour", "Lord", "")
INSERT INTO _table_ Values("Hollins", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Hollis of Heigham", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Home", "Conservative", "Earl", "")
INSERT INTO _table_ Values("Hooper", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Hope of Craighead", "Other", "Lord", "")
INSERT INTO _table_ Values("Hope of Thornes", "Other", "Lord", "")
INSERT INTO _table_ Values("Howard of Lympne", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Howard of Rising", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Howarth of Breckland", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Howarth of Newport", "Labour", "Lord", "")
INSERT INTO _table_ Values("Howe of Aberavon", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Howe of Idlicote", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Howell of Guildford", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Howells of St Davids", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Howie of Troon", "Labour", "Lord", "")
INSERT INTO _table_ Values("Hoyle", "Labour", "Lord", "")
INSERT INTO _table_ Values("Hughes of Stretford", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Hughes of Woodside", "Labour", "Lord", "")
INSERT INTO _table_ Values("Hunt of Chesterton", "Labour", "Lord", "")
INSERT INTO _table_ Values("Hunt of Kings Heath", "Labour", "Lord", "")
INSERT INTO _table_ Values("Hunt of Wirral", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Hurd of Westwell", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Hussain", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Hussein-Ece", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Hutton of Furness", "Labour", "Lord", "")
INSERT INTO _table_ Values("Hutton", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Hylton", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Imbert", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Inge", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Inglewood", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Irvine of Lairg", "Labour", "Lord", "")
INSERT INTO _table_ Values("Jacobs", "Non-affiliated (current Member)", "Lord", "")
INSERT INTO _table_ Values("James of Blackheath", "Conservative", "Lord", "")
INSERT INTO _table_ Values("James of Holland Park", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Janner of Braunstone", "Labour", "Lord", "")
INSERT INTO _table_ Values("Janvrin", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Jay of Ewelme", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Jay of Paddington", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Jenkin of Kennington", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Jenkin of Roding", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Joffe", "Labour", "Lord", "")
INSERT INTO _table_ Values("Jolly", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Jones of Birmingham", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Jones of Cheltenham", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Jones of Whitchurch", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Jones", "Labour", "Lord", "")
INSERT INTO _table_ Values("Jopling", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Jordan", "Labour", "Lord", "")
INSERT INTO _table_ Values("Judd", "Labour", "Lord", "")
INSERT INTO _table_ Values("Judge", "Other", "Lord", "")
INSERT INTO _table_ Values("Kakkar", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Kalms", "Non-affiliated (current Member)", "Lord", "")
INSERT INTO _table_ Values("Kennedy of The Shaws", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Kerr of Kinlochard", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Kerr of Tonaghmore", "Other", "Lord", "")
INSERT INTO _table_ Values("Kestenbaum", "Labour", "Lord", "")
INSERT INTO _table_ Values("Kidron", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Kilclooney", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Kilpatrick of Kincraig", "Other", "Lord", "")
INSERT INTO _table_ Values("Kimball", "Conservative", "Lord", "")
INSERT INTO _table_ Values("King of Bow", "Labour", "Baroness", "")
INSERT INTO _table_ Values("King of Bridgwater", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Kingsdown", "Other", "Lord", "")
INSERT INTO _table_ Values("Kingsmill", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Kinnock of Holyhead", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Kinnock", "Labour", "Lord", "")
INSERT INTO _table_ Values("Kirkham", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Kirkhill", "Labour", "Lord", "")
INSERT INTO _table_ Values("Kirkwood of Kirkhope", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Knight of Collingtree", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Knight of Weymouth", "Labour", "Lord", "")
INSERT INTO _table_ Values("Knights", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Kramer", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Krebs", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Laird", "Ulster Unionist Party", "Lord", "")
INSERT INTO _table_ Values("Laming", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Lamont of Lerwick", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Lang of Monkton", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Lawson of Blaby", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Layard", "Labour", "Lord", "")
INSERT INTO _table_ Values("Lea of Crondall", "Labour", "Lord", "")
INSERT INTO _table_ Values("Leach of Fairford", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Lee of Trafford", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Leicester", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Leitch", "Labour", "Lord", "")
INSERT INTO _table_ Values("Lester of Herne Hill", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Levene of Portsoken", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Levy", "Labour", "Lord", "")
INSERT INTO _table_ Values("Lewis of Newnham", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Lexden", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Lichfield", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Liddell of Coatdyke", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Liddle", "Labour", "Lord", "")
INSERT INTO _table_ Values("Lindsay", "Conservative", "Earl", "")
INSERT INTO _table_ Values("Lingfield", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Linklater of Butterstone", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Lipsey", "Labour", "Lord", "")
INSERT INTO _table_ Values("Lister of Burtersett", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Listowel", "Crossbench", "Earl", "")
INSERT INTO _table_ Values("Liverpool", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Liverpool", "Conservative", "Earl", "")
INSERT INTO _table_ Values("Lloyd of Berwick", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Lloyd-Webber", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Lockwood", "Labour", "Baroness", "")
INSERT INTO _table_ Values("London", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Loomba", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Lothian", "Conservative", "Marquess", "")
INSERT INTO _table_ Values("Low of Dalston", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Luce", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Ludford", "Other", "Baroness", "")
INSERT INTO _table_ Values("Luke", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Lyell", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Lytton", "Crossbench", "Earl", "")
INSERT INTO _table_ Values("Macaulay of Bragar", "Other", "Lord", "")
INSERT INTO _table_ Values("Macdonald of River Glaven", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Macdonald of Tradeston", "Labour", "Lord", "")
INSERT INTO _table_ Values("Macfarlane of Bearsden", "Conservative", "Lord", "")
INSERT INTO _table_ Values("MacGregor of Pulham Market", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Mackay of Clashfern", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Mackay of Drumadoon", "Other", "Lord", "")
INSERT INTO _table_ Values("MacKenzie of Culkein", "Labour", "Lord", "")
INSERT INTO _table_ Values("Mackenzie of Framwellgate", "Labour", "Lord", "")
INSERT INTO _table_ Values("Mackie of Benshie", "Other", "Lord", "")
INSERT INTO _table_ Values("MacLaurin of Knebworth", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Maclennan of Rogart", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Maddock", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Magan of Castletown", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Maginnis of Drumglass", "Non-affiliated (current Member)", "Lord", "")
INSERT INTO _table_ Values("Mallalieu", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Malloch-Brown", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Mance", "Other", "Lord", "")
INSERT INTO _table_ Values("Mancroft", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Mandelson", "Labour", "Lord", "")
INSERT INTO _table_ Values("Manningham-Buller", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Mar and Kellie", "Liberal Democrat", "Earl", "")
INSERT INTO _table_ Values("Mar", "Crossbench", "Countess", "")
INSERT INTO _table_ Values("Marks of Henley-on-Thames", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Marland", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Marlesford", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Martin of Springburn", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Masham of Ilton", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Mason of Barnsley", "Other", "Lord", "")
INSERT INTO _table_ Values("Massey of Darwen", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Mawhinney", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Mawson", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Maxton", "Labour", "Lord", "")
INSERT INTO _table_ Values("May of Oxford", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Mayhew of Twysden", "Conservative", "Lord", "")
INSERT INTO _table_ Values("McAvoy", "Labour", "Lord", "")
INSERT INTO _table_ Values("McCluskey", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("McColl of Dulwich", "Conservative", "Lord", "")
INSERT INTO _table_ Values("McDonagh", "Labour", "Baroness", "")
INSERT INTO _table_ Values("McFall of Alcluith", "Labour", "Lord", "")
INSERT INTO _table_ Values("McIntosh of Hudnall", "Labour", "Baroness", "")
INSERT INTO _table_ Values("McKenzie of Luton", "Labour", "Lord", "")
INSERT INTO _table_ Values("Meacher", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Methuen", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Miller of Chilthorne Domer", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Miller of Hendon", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Millett", "Other", "Lord", "")
INSERT INTO _table_ Values("Mitchell", "Labour", "Lord", "")
INSERT INTO _table_ Values("Mogg", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Molyneaux of Killead", "Other", "Lord", "")
INSERT INTO _table_ Values("Monks", "Labour", "Lord", "")
INSERT INTO _table_ Values("Montagu of Beaulieu", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Montgomery of Alamein", "Crossbench", "Viscount", "")
INSERT INTO _table_ Values("Montrose", "Conservative", "Duke", "")
INSERT INTO _table_ Values("Moonie", "Labour", "Lord", "")
INSERT INTO _table_ Values("Moore of Lower Marsh", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Moran", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Morgan of Drefelin", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Morgan of Ely", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Morgan of Huyton", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Morgan", "Labour", "Lord", "")
INSERT INTO _table_ Values("Morris of Aberavon", "Labour", "Lord", "")
INSERT INTO _table_ Values("Morris of Bolton", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Morris of Handsworth", "Labour", "Lord", "")
INSERT INTO _table_ Values("Morris of Yardley", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Morrow", "Democratic Unionist", "Lord", "")
INSERT INTO _table_ Values("Moser", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Moynihan", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Murphy", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Mustill", "Other", "Lord", "")
INSERT INTO _table_ Values("Myners", "Labour", "Lord", "")
INSERT INTO _table_ Values("Naseby", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Nash", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Neill of Bladen", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Neuberger of Abbotsbury", "Other", "Lord", "")
INSERT INTO _table_ Values("Neuberger", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Neville-Jones", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Newcastle", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Newlove", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Nicholls of Birkenhead", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Nicholson of Winterbourne", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Nickson", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Nicol", "Other", "Baroness", "")
INSERT INTO _table_ Values("Noakes", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Noon", "Labour", "Lord", "")
INSERT INTO _table_ Values("Norfolk", "Other", "Duke", "")
INSERT INTO _table_ Values("Northbourne", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Northbrook", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Northfield", "Other", "Lord", "")
INSERT INTO _table_ Values("Norwich", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Nye", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Oakeshott of Seagrove Bay", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("O'Cathain", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("O'Donnell", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("O'Loan", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("O'Neill of Bengarve", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("O'Neill of Clackmannan", "Labour", "Lord", "")
INSERT INTO _table_ Values("Oppenheim-Barnes", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Ouseley", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Owen", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Oxburgh", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Oxford", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Paisley of St George's", "Democratic Unionist", "Baroness", "")
INSERT INTO _table_ Values("Palmer of Childs Hill", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Palmer", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Palumbo", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Pannick", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Parekh", "Labour", "Lord", "")
INSERT INTO _table_ Values("Parkinson", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Parminter", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Patel of Blackburn", "Labour", "Lord", "")
INSERT INTO _table_ Values("Patel of Bradford", "Labour", "Lord", "")
INSERT INTO _table_ Values("Patel", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Patten of Barnes", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Patten", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Paul", "Non-affiliated (current Member)", "Lord", "")
INSERT INTO _table_ Values("Pearson of Rannoch", "UK Independence Party", "Lord", "")
INSERT INTO _table_ Values("Peel", "Crossbench", "Earl", "")
INSERT INTO _table_ Values("Pendry", "Labour", "Lord", "")
INSERT INTO _table_ Values("Perry of Southwark", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Peston", "Labour", "Lord", "")
INSERT INTO _table_ Values("Phillips of Sudbury", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Phillips of Worth Matravers", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Pitkeathley", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Plant of Highfield", "Labour", "Lord", "")
INSERT INTO _table_ Values("Platt of Writtle", "Other", "Baroness", "")
INSERT INTO _table_ Values("Plumb", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Ponsonby of Shulbrede", "Labour", "Lord", "")
INSERT INTO _table_ Values("Popat", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Powell of Bayswater", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Prashar", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Prior", "Other", "Lord", "")
INSERT INTO _table_ Values("Prosser", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Prys-Davies", "Other", "Lord", "")
INSERT INTO _table_ Values("Puttnam", "Labour", "Lord", "")
INSERT INTO _table_ Values("Quin", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Quirk", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Radice", "Labour", "Lord", "")
INSERT INTO _table_ Values("Ramsay of Cartvale", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Ramsbotham", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Rana", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Randerson", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Razzall", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Rea", "Labour", "Lord", "")
INSERT INTO _table_ Values("Reay", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Redesdale", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Rees of Ludlow", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Reid of Cardowan", "Labour", "Lord", "")
INSERT INTO _table_ Values("Rendell of Babergh", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Renfrew of Kaimsthorn", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Renton of Mount Harry", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Renwick of Clifton", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Ribeiro", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Richard", "Labour", "Lord", "")
INSERT INTO _table_ Values("Richardson of Calow", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Ripon and Leeds", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Risby", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Rix", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Roberts of Conwy", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Roberts of Llandudno", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Robertson of Port Ellen", "Labour", "Lord", "")
INSERT INTO _table_ Values("Rodgers of Quarry Bank", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Rogan", "Ulster Unionist Party", "Lord", "")
INSERT INTO _table_ Values("Rogers of Riverside", "Labour", "Lord", "")
INSERT INTO _table_ Values("Rooker", "Labour Independent", "Lord", "")
INSERT INTO _table_ Values("Roper", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Rosser", "Labour", "Lord", "")
INSERT INTO _table_ Values("Rosslyn", "Crossbench", "Earl", "")
INSERT INTO _table_ Values("Rotherwick", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Rowe-Beddoe", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Rowlands", "Labour", "Lord", "")
INSERT INTO _table_ Values("Ryder of Wensum", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Saatchi", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Sainsbury of Preston Candover", "Other", "Lord", "")
INSERT INTO _table_ Values("Sainsbury of Turville", "Labour", "Lord", "")
INSERT INTO _table_ Values("Salisbury", "Other", "Marquess", "")
INSERT INTO _table_ Values("Saltoun of Abernethy", "Crossbench", "Lady", "")
INSERT INTO _table_ Values("Sandberg", "Other", "Lord", "")
INSERT INTO _table_ Values("Sanderson of Bowden", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Sandwich", "Crossbench", "Earl", "")
INSERT INTO _table_ Values("Saville of Newdigate", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Sawyer", "Labour", "Lord", "")
INSERT INTO _table_ Values("Scotland of Asthal", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Scott of Foscote", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Scott of Needham Market", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Seccombe", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Selborne", "Conservative", "Earl", "")
INSERT INTO _table_ Values("Selkirk of Douglas", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Selsdon", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Sewel", "Non-affiliated (current Member)", "Lord", "")
INSERT INTO _table_ Values("Shackleton of Belgravia", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Sharkey", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Sharman", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Sharp of Guildford", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Sharples", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Shaw of Northstead", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Sheikh", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Sheldon", "Labour", "Lord", "")
INSERT INTO _table_ Values("Shephard of Northwold", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Sheppard of Didgemere", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Sherlock", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Shipley", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Shrewsbury", "Conservative", "Earl", "")
INSERT INTO _table_ Values("Shutt of Greetland", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Simon of Highbury", "Other", "Lord", "")
INSERT INTO _table_ Values("Simon", "Labour", "Viscount", "")
INSERT INTO _table_ Values("Simpson of Dunkeld", "Other", "Lord", "")
INSERT INTO _table_ Values("Singh of Wimbledon", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Skelmersdale", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Skidelsky", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Slim", "Crossbench", "Viscount", "")
INSERT INTO _table_ Values("Smith of Basildon", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Smith of Clifton", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Smith of Finsbury", "Non-affiliated (current Member)", "Lord", "")
INSERT INTO _table_ Values("Smith of Gilmorehill", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Smith of Kelvin", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Smith of Leigh", "Labour", "Lord", "")
INSERT INTO _table_ Values("Snape", "Labour", "Lord", "")
INSERT INTO _table_ Values("Snowdon", "Other", "Earl", "")
INSERT INTO _table_ Values("Soley", "Labour", "Lord", "")
INSERT INTO _table_ Values("Soulsby of Swaffham Prior", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Spicer", "Conservative", "Lord", "")
INSERT INTO _table_ Values("St Edmundsbury and Ipswich", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("St John of Bletso", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Stair", "Crossbench", "Earl", "")
INSERT INTO _table_ Values("Stedman-Scott", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Steel of Aikwood", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Stephen", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Sterling of Plaistow", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Stern of Brentford", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Stern", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Stevens of Kirkwhelpington", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Stevens of Ludgate", "Conservative Independent", "Lord", "")
INSERT INTO _table_ Values("Stevenson of Balmacara", "Labour", "Lord", "")
INSERT INTO _table_ Values("Stevenson of Coddenham", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Stewartby", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Steyn", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Stirrup", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Stoddart of Swindon", "Independent Labour", "Lord", "")
INSERT INTO _table_ Values("Stone of Blackheath", "Labour", "Lord", "")
INSERT INTO _table_ Values("Stoneham of Droxford", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Sutherland of Houndwood", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Swinfen", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Symons of Vernham Dean", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Tanlaw", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Taverne", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Taylor of Blackburn", "Labour", "Lord", "")
INSERT INTO _table_ Values("Taylor of Bolton", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Taylor of Goss Moor", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Taylor of Warwick", "Non-affiliated (current Member)", "Lord", "")
INSERT INTO _table_ Values("Tebbit", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Templeman", "Other", "Lord", "")
INSERT INTO _table_ Values("Temple-Morris", "Labour", "Lord", "")
INSERT INTO _table_ Values("Tenby", "Crossbench", "Viscount", "")
INSERT INTO _table_ Values("Thatcher", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Thomas of Gresford", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Thomas of Macclesfield", "Other", "Lord", "")
INSERT INTO _table_ Values("Thomas of Swynnerton", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Thomas of Walliswood", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Thomas of Winchester", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Thornton", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Tombs", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Tomlinson", "Labour", "Lord", "")
INSERT INTO _table_ Values("Tonge", "Independent Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Tope", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Tordoff", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Touhig", "Labour", "Lord", "")
INSERT INTO _table_ Values("Trees", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Trefgarne", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Trenchard", "Conservative", "Viscount", "")
INSERT INTO _table_ Values("Triesman", "Labour", "Lord", "")
INSERT INTO _table_ Values("Trimble", "Conservative", "Lord", "")
INSERT INTO _table_ Values("True", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Trumpington", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Truro", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Truscott", "Non-affiliated (current Member)", "Lord", "")
INSERT INTO _table_ Values("Tugendhat", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Tunnicliffe", "Labour", "Lord", "")
INSERT INTO _table_ Values("Turnberg", "Labour", "Lord", "")
INSERT INTO _table_ Values("Turnbull", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Turner of Camden", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Turner of Ecchinswell", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Tyler of Enfield", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Tyler", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Uddin", "Non-affiliated (current Member)", "Baroness", "")
INSERT INTO _table_ Values("Ullswater", "Conservative", "Viscount", "")
INSERT INTO _table_ Values("Vadera", "Other", "Baroness", "")
INSERT INTO _table_ Values("Valentine", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Vallance of Tummel", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Vincent of Coleshill", "Other", "Lord", "")
INSERT INTO _table_ Values("Vinson", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Waddington", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Wade of Chorlton", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Wakefield", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Wakeham", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Waldegrave of North Hill", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Walker of Aldringham", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Walker of Gestingthorpe", "Other", "Lord", "")
INSERT INTO _table_ Values("Wall of New Barnet", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Wallace of Tankerness", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Walmsley", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Walpole", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Walton of Detchant", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Warner", "Labour", "Lord", "")
INSERT INTO _table_ Values("Warnock", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Warsi", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Warwick of Undercliffe", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Wasserman", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Watson of Invergowrie", "Labour", "Lord", "")
INSERT INTO _table_ Values("Watson of Richmond", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Waverley", "Crossbench", "Viscount", "")
INSERT INTO _table_ Values("Wei", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Weidenfeld", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("West of Spithead", "Labour", "Lord", "")
INSERT INTO _table_ Values("Wheatcroft", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Wheeler", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Whitaker", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Whitty", "Labour", "Lord", "")
INSERT INTO _table_ Values("Wigley", "Plaid Cymru", "Lord", "")
INSERT INTO _table_ Values("Wilcox", "Conservative", "Baroness", "")
INSERT INTO _table_ Values("Wilkins", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Williams of Baglan", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Williams of Crosby", "Liberal Democrat", "Baroness", "")
INSERT INTO _table_ Values("Williams of Elvel", "Labour", "Lord", "")
INSERT INTO _table_ Values("Williams of Oystermouth", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Williamson of Horton", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Willis of Knaresborough", "Liberal Democrat", "Lord", "")
INSERT INTO _table_ Values("Willoughby de Broke", "UK Independence Party", "Lord", "")
INSERT INTO _table_ Values("Wills", "Labour", "Lord", "")
INSERT INTO _table_ Values("Wilson of Dinton", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Wilson of Tillyorn", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Winchester", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Winston", "Labour", "Lord", "")
INSERT INTO _table_ Values("Wolfson of Aspley Guise", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Wolfson of Sunningdale", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Wood of Anfield", "Labour", "Lord", "")
INSERT INTO _table_ Values("Woolf", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("Woolmer of Leeds", "Labour", "Lord", "")
INSERT INTO _table_ Values("Worcester", "Bishops", "Bishop", "")
INSERT INTO _table_ Values("Worthington", "Labour", "Baroness", "")
INSERT INTO _table_ Values("Wright of Richmond", "Crossbench", "Lord", "")
INSERT INTO _table_ Values("York", "Bishops", "Archbishop", "")
INSERT INTO _table_ Values("Young of Graffham", "Conservative", "Lord", "")
INSERT INTO _table_ Values("Young of Hornsey", "Crossbench", "Baroness", "")
INSERT INTO _table_ Values("Young of Norwood Green", "Labour", "Lord", "")
INSERT INTO _table_ Values("Young of Old Scone", "Non-affiliated (current Member)", "Baroness", "")
INSERT INTO _table_ Values("Younger of Leckie", "Conservative", "Viscount", "")