
INSERT INTO _table_ Values ("afneil", "N/A", "", "@afneil")
INSERT INTO _table_ Values ("alistair heath", "N/A", "", "@alistairheath")
INSERT INTO _table_ Values ("andrew comres", "N/A", "", "@andrew_comres")
INSERT INTO _table_ Values ("andrew sparrow", "N/A", "", "@andrewsparrow")
INSERT INTO _table_ Values ("anntreneman", "N/A", "", "@anntreneman")
INSERT INTO _table_ Values ("Alan Rudbridger", "N/A", "", "@arusbridger")
INSERT INTO _table_ Values ("bbc normans", "N/A", "", "@bbcnormans")
INSERT INTO _table_ Values ("Org: bbcpolitics", "N/A", "", "@bbcpolitics")
INSERT INTO _table_ Values ("Org: bbcr4today", "N/A", "", "@bbcr4today")
INSERT INTO _table_ Values ("campbellclaret", "N/A", "", "@campbellclaret")
INSERT INTO _table_ Values ("Org: channel4news", "N/A", "", "@channel4news")
INSERT INTO _table_ Values ("chrisshipitv", "N/A", "", "@chrisshipitv")
INSERT INTO _table_ Values ("craiga woodhouse", "N/A", "", "@craigawoodhouse")
INSERT INTO _table_ Values ("gallagher editor", "N/A", "", "@gallaghereditor")
INSERT INTO _table_ Values ("Paul Staines", "N/A", "", "@GuidoFawkes")
INSERT INTO _table_ Values ("iain dale", "N/A", "", "@iaindale")
INSERT INTO _table_ Values ("ian katz", "N/A", "", "@iankatz1000")
INSERT INTO _table_ Values ("Org: ipsosmori", "N/A", "", "@ipsosmori")
INSERT INTO _table_ Values ("Org: ipsosmori ", "N/A", "", "@ipsosmori ")
INSERT INTO _table_ Values ("Laura Kuenssberg", "N/A", "", "@ITVLauraK")
INSERT INTO _table_ Values ("james chappers", "N/A", "", "@jameschappers")
INSERT INTO _table_ Values ("jg forsyth", "N/A", "", "@jgforsyth")
INSERT INTO _table_ Values ("joe murphy london", "N/A", "", "@joemurphylondon")
INSERT INTO _table_ Values ("Johann Hari", "N/A", "", "@johannhari101")
INSERT INTO _table_ Values ("John Rentoul", "N/A", "", "@JohnRentoul")
INSERT INTO _table_ Values ("johnrentoul", "N/A", "", "@johnrentoul")
INSERT INTO _table_ Values ("Jon Snow", "N/A", "", "@jonsnowC4")
INSERT INTO _table_ Values ("kiran stacey", "N/A", "", "@kiranstacey")
INSERT INTO _table_ Values ("Lucy Marcus", "N/A", "", "@lucymarcus")
INSERT INTO _table_ Values ("Org: mailonline", "N/A", "", "@mailonline")
INSERT INTO _table_ Values ("msmithsonPB", "N/A", "", "@msmithsonPB")
INSERT INTO _table_ Values ("mtharry cole", "N/A", "", "@mtharrycole")
INSERT INTO _table_ Values ("nick ferrarilbc", "N/A", "", "@nickferrarilbc")
INSERT INTO _table_ Values ("oflynn express", "N/A", "", "@oflynnexpress")
INSERT INTO _table_ Values ("patrick wintour", "N/A", "", "@patrickwintour")
INSERT INTO _table_ Values ("Paul Waugh", "N/A", "", "@paulwaugh")
INSERT INTO _table_ Values ("pcollins times", "N/A", "", "@pcollinstimes")
INSERT INTO _table_ Values ("Robert Peston", "N/A", "", "@Peston")
INSERT INTO _table_ Values ("Phillip Blond", "N/A", "", "@Phillip_Blond")
INSERT INTO _table_ Values ("Org: politicalbeting", "N/A", "", "@politicalbeting")
INSERT INTO _table_ Values ("Org: politicshomeuk", "N/A", "", "@politicshomeuk")
INSERT INTO _table_ Values ("Brian Cox", "N/A", "", "@ProfBrianCox")
INSERT INTO _table_ Values ("Richard Dawkins", "N/A", "", "@RichardDawkins")
INSERT INTO _table_ Values ("roland watson", "N/A", "", "@rolandwatson66")
INSERT INTO _table_ Values ("sand standard", "N/A", "", "@sandstandard")
INSERT INTO _table_ Values ("Sarah Brown", "N/A", "", "@SarahBrownUK")
INSERT INTO _table_ Values ("Org: skynews", "N/A", "", "@skynews")
INSERT INTO _table_ Values ("sophyridgesky", "N/A", "", "@sophyridgesky")
INSERT INTO _table_ Values ("Sunder Katwala", "N/A", "", "@sundersays")
INSERT INTO _table_ Values ("Org: telepolitics", "N/A", "", "@telepolitics")
INSERT INTO _table_ Values ("Org: theeconomist", "N/A", "", "@theeconomist")
INSERT INTO _table_ Values ("tim montgomerie", "N/A", "", "@timmontgomerie")
INSERT INTO _table_ Values ("tnewtondunn", "N/A", "", "@tnewtondunn")
INSERT INTO _table_ Values ("toad meister", "N/A", "", "@toadmeister")
INSERT INTO _table_ Values ("Org: yougov", "N/A", "", "@yougov")
INSERT INTO _table_ Values ("Zee Kane", "N/A", "", "@Zee")
