INSERT INTO website_media VALUES (DEFAULT, 'afneil', 'N/A', 'N/A', '@afneil')
INSERT INTO website_media VALUES (DEFAULT, 'alistair heath', 'N/A', 'N/A', '@alistairheath')
INSERT INTO website_media VALUES (DEFAULT, 'andrew comres', 'N/A', 'N/A', '@andrew_comres')
INSERT INTO website_media VALUES (DEFAULT, 'andrew sparrow', 'N/A', 'N/A', '@andrewsparrow')
INSERT INTO website_media VALUES (DEFAULT, 'anntreneman', 'N/A', 'N/A', '@anntreneman')
INSERT INTO website_media VALUES (DEFAULT, 'Alan Rudbridger', 'N/A', 'N/A', '@arusbridger')
INSERT INTO website_media VALUES (DEFAULT, 'bbc normans', 'N/A', 'N/A', '@bbcnormans')
INSERT INTO website_media VALUES (DEFAULT, 'Org: bbcpolitics', 'N/A', 'N/A', '@bbcpolitics')
INSERT INTO website_media VALUES (DEFAULT, 'Org: bbcr4today', 'N/A', 'N/A', '@bbcr4today')
INSERT INTO website_media VALUES (DEFAULT, 'campbellclaret', 'N/A', 'N/A', '@campbellclaret')
INSERT INTO website_media VALUES (DEFAULT, 'Org: channel4news', 'N/A', 'N/A', '@channel4news')
INSERT INTO website_media VALUES (DEFAULT, 'chrisshipitv', 'N/A', 'N/A', '@chrisshipitv')
INSERT INTO website_media VALUES (DEFAULT, 'craiga woodhouse', 'N/A', 'N/A', '@craigawoodhouse')
INSERT INTO website_media VALUES (DEFAULT, 'gallagher editor', 'N/A', 'N/A', '@gallaghereditor')
INSERT INTO website_media VALUES (DEFAULT, 'Paul Staines', 'N/A', 'N/A', '@GuidoFawkes')
INSERT INTO website_media VALUES (DEFAULT, 'iain dale', 'N/A', 'N/A', '@iaindale')
INSERT INTO website_media VALUES (DEFAULT, 'ian katz', 'N/A', 'N/A', '@iankatz1000')
INSERT INTO website_media VALUES (DEFAULT, 'Org: ipsosmori', 'N/A', 'N/A', '@ipsosmori')
INSERT INTO website_media VALUES (DEFAULT, 'Org: ipsosmori ', 'N/A', 'N/A', '@ipsosmori ')
INSERT INTO website_media VALUES (DEFAULT, 'Laura Kuenssberg', 'N/A', 'N/A', '@ITVLauraK')
INSERT INTO website_media VALUES (DEFAULT, 'james chappers', 'N/A', 'N/A', '@jameschappers')
INSERT INTO website_media VALUES (DEFAULT, 'jg forsyth', 'N/A', 'N/A', '@jgforsyth')
INSERT INTO website_media VALUES (DEFAULT, 'joe murphy london', 'N/A', 'N/A', '@joemurphylondon')
INSERT INTO website_media VALUES (DEFAULT, 'Johann Hari', 'N/A', 'N/A', '@johannhari101')
INSERT INTO website_media VALUES (DEFAULT, 'John Rentoul', 'N/A', 'N/A', '@JohnRentoul')
INSERT INTO website_media VALUES (DEFAULT, 'johnrentoul', 'N/A', 'N/A', '@johnrentoul')
INSERT INTO website_media VALUES (DEFAULT, 'Jon Snow', 'N/A', 'N/A', '@jonsnowC4')
INSERT INTO website_media VALUES (DEFAULT, 'kiran stacey', 'N/A', 'N/A', '@kiranstacey')
INSERT INTO website_media VALUES (DEFAULT, 'Lucy Marcus', 'N/A', 'N/A', '@lucymarcus')
INSERT INTO website_media VALUES (DEFAULT, 'Org: mailonline', 'N/A', 'N/A', '@mailonline')
INSERT INTO website_media VALUES (DEFAULT, 'msmithsonPB', 'N/A', 'N/A', '@msmithsonPB')
INSERT INTO website_media VALUES (DEFAULT, 'mtharry cole', 'N/A', 'N/A', '@mtharrycole')
INSERT INTO website_media VALUES (DEFAULT, 'nick ferrarilbc', 'N/A', 'N/A', '@nickferrarilbc')
INSERT INTO website_media VALUES (DEFAULT, 'oflynn express', 'N/A', 'N/A', '@oflynnexpress')
INSERT INTO website_media VALUES (DEFAULT, 'patrick wintour', 'N/A', 'N/A', '@patrickwintour')
INSERT INTO website_media VALUES (DEFAULT, 'Paul Waugh', 'N/A', 'N/A', '@paulwaugh')
INSERT INTO website_media VALUES (DEFAULT, 'pcollins times', 'N/A', 'N/A', '@pcollinstimes')
INSERT INTO website_media VALUES (DEFAULT, 'Robert Peston', 'N/A', 'N/A', '@Peston')
INSERT INTO website_media VALUES (DEFAULT, 'Phillip Blond', 'N/A', 'N/A', '@Phillip_Blond')
INSERT INTO website_media VALUES (DEFAULT, 'Org: politicalbeting', 'N/A', 'N/A', '@politicalbeting')
INSERT INTO website_media VALUES (DEFAULT, 'Org: politicshomeuk', 'N/A', 'N/A', '@politicshomeuk')
INSERT INTO website_media VALUES (DEFAULT, 'Brian Cox', 'N/A', 'N/A', '@ProfBrianCox')
INSERT INTO website_media VALUES (DEFAULT, 'Richard Dawkins', 'N/A', 'N/A', '@RichardDawkins')
INSERT INTO website_media VALUES (DEFAULT, 'roland watson', 'N/A', 'N/A', '@rolandwatson66')
INSERT INTO website_media VALUES (DEFAULT, 'sand standard', 'N/A', 'N/A', '@sandstandard')
INSERT INTO website_media VALUES (DEFAULT, 'Sarah Brown', 'N/A', 'N/A', '@SarahBrownUK')
INSERT INTO website_media VALUES (DEFAULT, 'Org: skynews', 'N/A', 'N/A', '@skynews')
INSERT INTO website_media VALUES (DEFAULT, 'sophyridgesky', 'N/A', 'N/A', '@sophyridgesky')
INSERT INTO website_media VALUES (DEFAULT, 'Sunder Katwala', 'N/A', 'N/A', '@sundersays')
INSERT INTO website_media VALUES (DEFAULT, 'Org: telepolitics', 'N/A', 'N/A', '@telepolitics')
INSERT INTO website_media VALUES (DEFAULT, 'Org: theeconomist', 'N/A', 'N/A', '@theeconomist')
INSERT INTO website_media VALUES (DEFAULT, 'tim montgomerie', 'N/A', 'N/A', '@timmontgomerie')
INSERT INTO website_media VALUES (DEFAULT, 'tnewtondunn', 'N/A', 'N/A', '@tnewtondunn')
INSERT INTO website_media VALUES (DEFAULT, 'toad meister', 'N/A', 'N/A', '@toadmeister')
INSERT INTO website_media VALUES (DEFAULT, 'Org: yougov', 'N/A', 'N/A', '@yougov')
INSERT INTO website_media VALUES (DEFAULT, 'Zee Kane', 'N/A', 'N/A', '@Zee')
