INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Robert Buckland MP', 'Conservative', 'South Swindon', '@RobertBuckland')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Adam Afriyie', 'Conservative', 'Windsor', '@AdamAfriyie')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Adrian Bailey', 'Labour', 'West Bromwich West', '@Adrian_Bailey')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Adrian Sanders', 'Liberal Democrats', 'Torbay', '@adriansandersmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Aidan Burley MP', 'Conservative', 'Cannock Chase', '@AidanBurleyMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Alan Duncan', 'Conservative', 'Rutland and Melton', '@AlanDuncan4MP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Alan Whitehead MP', 'Labour', 'Southampton, Test', '@alanwhiteheadmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Alasdair McDonnell', 'SDLP', 'Belfast South', '@AMcDonnellMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Alec Shelbrooke', 'Conservative', 'Elmet and Rothwell', '@AlecShelbrooke')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Alex Cunningham', 'Labour', 'Stockton North', '@ACunninghamMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Alison McGovern', 'Labour', 'Wirral South', '@Alison_McGovern')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('AlisonSeabeckMP', 'Labour', 'Plymouth, Devonport', '@alisonseabeck')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Alistair Carmichael', 'Liberal Democrats', 'Orkney and Shetland', '@acarmichaelmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Alun Cairns', 'Conservative', 'Vale of Glamorgan', '@AlunCairns')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Amber Rudd', 'Conservative', 'Hastings and Rye', '@AmberRuddMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('AnasSarwar', 'Labour', 'Glasgow Central', '@AnasSarwar')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Andrea Leadsom', 'Conservative', 'South Northamptonshire', '@andrealeadsom')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Andrew Bingham MP', 'Conservative', 'High Peak', '@HighPeakAndrew')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Andrew Bridgen MP', 'Conservative', 'North West Leicestershire', '@AndrewBridgenMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Andrew George', 'Liberal Democrats', 'St Ives', '@AndrewGeorgeLD')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Andrew Griffiths MP', 'Conservative', 'Burton', '@agriffithsmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Andrew Gwynne MP', 'Labour', 'Denton and Reddish', '@GwynneMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Andrew Jones MP', 'Conservative', 'Harrogate and Knaresborough', '@AndrewJonesMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Andrew Miller MP', 'Labour', 'Ellesmere Port and Neston', '@APMiller1949')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Andrew Percy', 'Conservative', 'Brigg and Goole', '@andrewpercy')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Andrew Rosindell MP', 'Conservative', 'Romford', '@AndrewRosindell')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Andrew Selous MP', 'Conservative', 'South West Bedfordshire', '@Andrew_SelousMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Andrew Stephenson MP', 'Conservative', 'Pendle', '@Andrew4Pendle')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Andy Burnham', 'Labour', 'Leigh', '@leighmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Andy Sawford MP', '', 'Corby', '@AndySawfordMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Andy Slaughter MP', 'Labour', 'Hammersmith', '@hammersmithandy')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Angela Eagle', 'Labour', 'Wallasey', '@angelaeagle')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Angie Bray', 'Conservative', 'Ealing Central and Acton', '@AngieBrayMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Angus MacNeil', 'SNP', 'Na h-Eileanan an Iar', '@AngusMacNeilMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Angus Robertson', 'SNP', 'Moray', '@MorayMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Ann Coffey MP', 'Labour', 'Stockport', '@anncoffey_mp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Ann McKechin', 'Labour', 'Glasgow North', '@AnnMcKechinMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Anna Soubry MP', 'Conservative', 'Broxtowe', '@Anna_SoubryMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Anne Marie Morris', 'Conservative', 'Newton Abbot', '@AMMorrisMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Anne McGuire MP', 'Labour', 'Stirling', '@AnneMcGuireMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Anne McIntosh', '', 'Thirsk and Malton', '@AnneMcIntoshMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Anne Milton MP', 'Conservative', 'Guildford', '@AnneMiltonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Annette Brooke', 'Liberal Democrats', 'Mid Dorset and North Poole', '@Annette4MDNP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Austin Mitchell', 'Labour', 'Great Grimsby', '@AVMitchell2010')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Barbara Keeley', 'Labour', 'Worsley', '@KeeleyMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Barry Gardiner MP', 'Labour', 'Brent North', '@BarryGardiner')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Barry Sheerman', 'Labour', 'Huddersfield', '@BSheermanMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Ben Bradshaw', 'Labour', 'Exeter', '@BenPBradshaw')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Ben Gummer', 'Conservative', 'Ipswich', '@ben4ipswich')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Bernard Jenkin MP', 'Conservative', 'North Essex', '@bernardjenkin')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Bill Cash', 'Conservative', 'Stone', '@BillCashMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Bill Esterson', 'Labour', 'Sefton Central', '@BillEstersonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Bob Ainsworth', 'Labour', 'Coventry North East', '@BobAinsworthMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Brandon Lewis MP', 'Conservative', 'Great Yarmouth', '@BrandonLewis')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Bridget Phillipson', 'Labour', 'Houghton and Sunderland South', '@bphillipsonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Brooks Newmark MP', 'Conservative', 'Braintree', '@TweetBrooks')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Caroline Flint', 'Labour', 'Don Valley', '@CarolineFlintMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Caroline Lucas', 'Green Party', 'Brighton, Pavilion', '@CarolineLucas')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Caroline Nokes', 'Conservative', 'Romsey and Southampton North', '@carolinenokes')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Catherine McKinnell', 'Labour', 'Newcastle upon Tyne North', '@CatMcKinnellMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Charles Kennedy', 'Liberal Democrats', 'Ross, Skye and Lochaber', '@charles_kennedy')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Charlie Elphicke', 'Conservative', 'Dover', '@CharlieElphicke')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Charlotte Leslie MP', 'Conservative', 'Bristol North West', '@CLeslieMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Cheryl Gillan MP', 'Conservative', 'Chesham and Amersham', '@CherylGillanMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Chloe Smith', 'Conservative', 'Norwich North', '@ChloeSmithMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Chris Bryant', 'Labour', 'Rhondda', '@ChrisBryantMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Chris Heaton-Harris', 'Conservative', 'Daventry', '@chhcalling')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Chris Leslie', 'Labour', 'Nottingham East', '@ChrisLeslieMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Chris Ruane MP', 'Labour', 'Vale of Clwyd', '@ChrisRuaneMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Chris Skidmore MP', 'Conservative', 'Kingswood', '@chrisskidmoremp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Chris White MP', 'Conservative', 'Warwick and Leamington', '@ChrisWhite_MP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Chris Williamson', 'Labour', 'Derby North', '@ChriswMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Christopher Huhne', 'Liberal Democrats', 'Eastleigh', '@ChrisHuhne')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Christopher Pincher', 'Conservative', 'Tamworth', '@ChrisPincher')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Chuka Umunna', 'Labour', 'Streatham', '@ChukaUmunna')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Claire Perry', 'Conservative', 'Devizes', '@claire4devizes')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Clive Betts', 'Labour', 'Sheffield, Attercliffe', '@CliveBettsMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Clive Efford', 'Labour', 'Eltham', '@CliveEfford')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Conor Burns MP', 'Conservative', 'Bournemouth West', '@Conor_BurnsMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Conor Murphy', 'Sinn Fein', 'Newry and Armagh', '@conormurphymp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Craig Whittaker', 'Conservative', 'Calder Valley', '@Craig_Whittaker')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Crispin Blunt', 'Conservative', 'Reigate', '@crispinbluntmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Dame Anne Begg MP', 'Labour', 'Aberdeen South', '@annebegg')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Damian', 'Conservative', 'Ashford', '@damiangreenmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Damian Hinds', 'Conservative', 'East Hampshire', '@damian57')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('DamianCollins', 'Conservative', 'Folkestone and Hythe', '@DamianCollins')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Dan Jarvis', 'Labour', 'Barnsley Central', '@DanJarvisMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Daniel Byles', 'Conservative', 'North Warwickshire', '@danielbyles')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Daniel Poulter', 'Conservative', 'Central Suffolk and North Ipswich', '@DrDanPoulter')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Danny Alexander', 'Liberal Democrats', 'Inverness, Nairn, Badenoch and Strathspey', '@dannyalexander')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('David Burrowes', 'Conservative', 'Enfield, Southgate', '@davidburrowesmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('David Cameron', 'Conservative', 'Witney', '@David_Cameron')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('David Evennett MP', 'Conservative', 'Bexleyheath and Crayford', '@DavidEvennett')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('David Hanson', 'Labour', 'Delyn', '@DavidHansonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('David Heath', 'Liberal Democrats', 'Somerton and Frome', '@DavidHeathMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('David Jones', 'Conservative', 'Clwyd West', '@DavidJonesMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('David Lammy', 'Labour', 'Tottenham', '@DavidLammy')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('David Lidington MP', 'Conservative', 'Aylesbury', '@DLidington')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('David Miliband', 'Labour', 'South Shields', '@DMiliband')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('David Morris MP', 'Conservative', 'Morecambe and Lunesdale', '@MPDavidMorris')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('David Mundell MP', 'Conservative', 'Dumfriesshire, Clydesdale and Tweeddale', '@DavidMundellMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('David Nuttall MP', 'Conservative', 'Bury North', '@DavidNuttallMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('David Rutley', 'Conservative', 'Macclesfield', '@DavidRutleyMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('David Ward', 'Liberal Democrats', 'Bradford East', '@DavidWardMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('David Wright MP', 'Labour', 'Telford', '@DavidWrightMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Debbie Abrahams', 'Labour', 'Oldham East and Saddleworth', '@Debbie_abrahams')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Denis MacShane', 'Labour', 'Rotherham', '@DenisMacShane')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Diana Johnson', 'Labour', 'Kingston upon Hull North', '@DianaJohnsonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Diane Abbott MP', 'Labour', 'Hackney North and Stoke Newington', '@HackneyAbbott')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Don Foster', 'Liberal Democrats', 'Bath', '@DonFosterMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Douglas Alexander', 'Labour', 'Paisley and Renfrewshire South', '@DAlexanderMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Douglas Carswell MP', 'Conservative', 'Harwich and North Essex', '@DouglasCarswell')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Dr Liam Fox MP', 'Conservative', 'Woodspring', '@LiamFoxMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Dr Phillip Lee MP', 'Conservative', 'Bracknell', '@DrPhillipLeeMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Duncan Hames', 'Liberal Democrats', 'Chippenham', '@duncanhames')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Ed Balls', 'Labour', 'Normanton', '@edballsmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Ed Miliband', 'Labour', 'Doncaster North', '@Ed_Miliband')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Ed Vaizey', 'Conservative', 'Wantage', '@edvaizey')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Edward Davey', 'Liberal Democrats', 'Kingston and Surbiton', '@eddaveykands')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Edward Leigh', 'Conservative', 'Gainsborough', '@edwardleighac')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Elizabeth Truss', 'Conservative', 'South West Norfolk', '@trussliz')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Emily Thornberry MP', 'Labour', 'Islington South and Finsbury', '@EmilyThornberry')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Emma Reynolds', 'Labour', 'Wolverhampton North East', '@EmmaReynoldsMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Eric Joyce MP', 'Labour', 'Falkirk', '@ericjoyce')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Eric Pickles', 'Conservative', 'Brentwood and Ongar', '@EricPickles')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Esther McVey', 'Conservative', 'Wirral West', '@EstherMcVeyMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Fabian Hamilton', 'Labour', 'Leeds North East', '@fabianhamilton')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Fiona O&#039;Donnell MP', 'Labour', 'East Lothian', '@FionaODonnellMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Frank Field&#039;s Team', 'Labour', 'Birkenhead', '@frankfieldteam')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Frank Roy', 'Labour', 'Motherwell and Wishaw', '@FrankRoyMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Gareth Thomas MP', 'Labour', 'Harrow West', '@GarethThomasMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Gavin Barwell MP', 'Conservative', 'Croydon Central', '@GavinBarwellMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Gavin Shuker', 'Labour', 'Luton South', '@gavinshuker')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Gavin Williamson MP', 'Conservative', 'South Staffordshire', '@GWilliamsonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Gemma Doyle', 'Labour', 'West Dunbartonshire', '@GemmaWDMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Geoffrey Cox MP', 'Conservative', 'Torridge and West Devon', '@Geoffrey_Cox')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('George Freeman MP', 'Conservative', 'Mid Norfolk', '@Freeman_George')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('George Hollingbery', 'Conservative', 'Meon Valley', '@George4MVMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Geraint Davies MP', 'Labour', 'Swansea West', '@GeraintDaviesMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Gerald Howarth', 'Conservative', 'Aldershot', '@geraldhowarth')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Gerry Sutcliffe', 'Labour', 'Bradford South', '@GSutcliffeMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Gisela', 'Labour', 'Birmingham, Edgbaston', '@GiselaStuart')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Glenda Jackson', 'Labour', 'Hampstead and Highgate', '@glendajacksonmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Gloria De Piero', 'Labour', 'Ashfield', '@GloriaDePieroMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Glyn Davies', 'Conservative', 'Montgomeryshire', '@GlynDaviesMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Gordon Birtwistle', 'Liberal Democrats', 'Burnley', '@GBirtwistle_MP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Gordon Henderson', 'Conservative', 'Sittingbourne and Sheppey', '@ghendersonmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Graham Allen MP', 'Labour', 'Nottingham North', '@GrahamAllenMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Graham Evans MP', 'Conservative', 'Weaver Vale', '@GrahamEvansMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Graham Jones', 'Labour', 'Hyndburn', '@GrahamJones_MP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Graham Stuart MP', 'Conservative', 'Beverley and Holderness', '@grahamstuart')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Grahame Morris', 'Labour', 'Easington', '@grahamemorris')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Grant Shapps MP', 'Conservative', 'Welwyn Hatfield', '@grantshapps')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Greg Barker', 'Conservative', 'Bexhill and Battle', '@GregBarkerMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Greg Clark', 'Conservative', 'Tunbridge Wells', '@gregclarkmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Greg Hands', 'Conservative', 'Chelsea and Fulham', '@GregHands')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Greg Knight', 'Conservative', 'East Yorkshire', '@gregknightmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Greg Mulholland', 'Liberal Democrats', 'Leeds North West', '@GregMulholland1')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Gregg McClymont MP', 'Labour', 'Cumbernauld, Kilsyth and Kirkintilloch East', '@greggmcclymont')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Guto Bebb', 'Conservative', 'Aberconwy', '@GutoBebb')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Harriet Harman', 'Labour', 'Camberwell and Peckham', '@HarrietHarman')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Harriett Baldwin', 'Conservative', 'West Worcestershire', '@HBaldwinMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Hazel Blears', 'Labour', 'Salford', '@HazelBlearsMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Heather Wheeler', 'Conservative', 'South Derbyshire', '@HeatherWheeler')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Heidi Alexander', 'Labour', 'Lewisham East', '@heidi_mp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Helen Goodman', 'Labour', 'Bishop Auckland', '@HelenGoodmanMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Helen Grant', 'Conservative', 'Maidstone and The Weald', '@helengrant1')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Helen Grant MP', 'Conservative', 'Maidstone and The Weald', '@HelenGrantMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Hilary Benn MP', 'Labour', 'Leeds Central', '@hilarybennmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Hugo Swire', 'Conservative', 'East Devon', '@HugoSwire')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Huw Irranca-Davies', 'Labour', 'Ogmore', '@IrrancaDaviesMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Hywel Williams', 'Plaid Cymru', 'Caernarfon', '@HywelWilliamsMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Iain McKenzie', 'Labour', 'Inverclyde', '@InverclydeMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Iain Stewart MP', 'Conservative', 'Milton Keynes South', '@iainastewart')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Iain Wright', 'Labour', 'Hartlepool', '@IainWrightMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Ian Austin', 'Labour', 'Dudley North', '@IanAustinMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Ian Davidson MP', 'Labour', 'Glasgow South West', '@IanDavidsonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Ian Lavery MP', 'Labour', 'Wansbeck', '@IanLaveryMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Ian Lucas', 'Labour', 'Wrexham', '@IanCLucas')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Ian Mearns MP', 'Labour', 'Gateshead', '@IanMearnsMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Ian Murray', 'Labour', 'Edinburgh South', '@IanMurrayMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Ian Swales', 'Liberal Democrats', 'Redcar', '@iswales')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Ivan Lewis', 'Labour', 'Bury South', '@IvanLewis_MP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('JackDromeyMP', 'Labour', 'Birmingham, Erdington', '@JackDromeyMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jake Berry', 'Conservative', 'Rossendale and Darwen', '@JakeBerryMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('James Brokenshire', 'Conservative', 'Hornchurch', '@JBrokenshire')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('James Duddridge', 'Conservative', 'Rochford and Southend East', '@JamesDuddridge')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('James Gray MP', 'Conservative', 'North Wiltshire', '@JamesGrayMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('James Morris', 'Conservative', 'Halesowen and Rowley Regis', '@JamesMorrisMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jamie Reed', 'Labour', 'Copeland', '@jreedmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jason McCartney MP', 'Conservative', 'Colne Valley', '@JasonMcCartney')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jeffrey M Donaldson', 'DUP', 'Lagan Valley', '@J_Donaldson_MP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jennifer Willott', 'Liberal Democrats', 'Cardiff Central', '@JennyWillott')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jenny Chapman MP', 'Labour', 'Darlington', '@JennyChapman')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jeremy Corbyn MP', 'Labour', 'Islington North', '@jeremycorbyn')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jeremy Hunt', 'Conservative', 'South West Surrey', '@Jeremy_Hunt')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jeremy Lefroy', 'Conservative', 'Stafford', '@JeremyLefroyMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jesse Norman', 'Conservative', 'Hereford and South Herefordshire', '@Jesse_Norman')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jessica Lee MP', 'Conservative', 'Erewash', '@JessicaLeeMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jim McGovern', 'Labour', 'Dundee West', '@JimMcGovernMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jim Murphy', 'Labour', 'Renfrewshire East', '@jimmurphymp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jim Sheridan', 'Labour', 'Paisley and Renfrewshire North', '@JimSheridanMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jo Johnson', 'Conservative', 'Orpington', '@JoJohnsonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jo Swinson', 'Liberal Democrats', 'East Dunbartonshire', '@joswinson')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('John Denham', 'Labour', 'Southampton, Itchen', '@JohnDenhamMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('John Glen', 'Conservative', 'Salisbury', '@JohnGlenMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('John Healey MP', 'Labour', 'Wentworth', '@JohnHealey_MP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('John Hemming', 'Liberal Democrats', 'Birmingham, Yardley', '@johnhemmingmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('John Leech', 'Liberal Democrats', 'Manchester, Withington', '@johnleechmcr')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('John Mann', 'Labour', 'Bassetlaw', '@JohnMannOffice')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('John McDonnell', 'Labour', 'Hayes and Harlington', '@johnmcdonnellMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('John Penrose MP', 'Conservative', 'Weston-Super-Mare', '@JohnPenroseNews')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('John Pugh', 'Liberal Democrats', 'Southport', '@johnpughmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('John Redwood', 'Conservative', 'Wokingham', '@johnredwood')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('John Robertson', 'Labour', 'Glasgow North West', '@JohnRobertsonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('John Stevenson MP', 'Conservative', 'Carlisle', '@JohnStevensonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('John Woodcock', 'Labour', 'Barrow and Furness', '@JWoodcockMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jon Cruddas', 'Labour', 'Dagenham', '@JonCruddasMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jon Trickett', 'Labour', 'Hemsworth', '@jon_trickett')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jonathan Ashworth MP', 'Labour', 'Leicester South', '@JonAshworth')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jonathan Djanogly', 'Conservative', 'Huntingdon', '@JDjanogly')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jonathan Edwards', 'Plaid Cymru', 'Carmarthen East and Dinefwr', '@JonathanPlaid')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jonathan Evans MP', 'Conservative', 'Cardiff North', '@JonathanEvansMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Jonathan Reynolds MP', 'Labour', 'Stalybridge and Hyde', '@jreynoldsMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Julian Huppert', 'Liberal Democrats', 'Cambridge', '@julianhuppert')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Julian Smith MP', 'Conservative', 'Skipton and Ripon', '@JulianSmithMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Julie Ann Hilling', 'Labour', 'Bolton West', '@JulieHillingMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Julie Elliott MP', 'Labour', 'Sunderland Central', '@JulieElliottMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Justin Tomlinson MP', 'Conservative', 'North Swindon', '@JTomlinsonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Karen Bradley', 'Conservative', 'Staffordshire Moorlands', '@karen__bradley')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Karen Buck', 'Labour', 'Regent&#039;s Park and Kensington North', '@KarenBuckMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Karl McCartney', 'Conservative', 'Lincoln', '@karlmccartney')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Karl Turner MP', 'Labour', 'Kingston upon Hull East', '@KarlTurnerMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Kate Green', 'Labour', 'Stretford and Urmston', '@KateGreenSU')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Keith Vaz MP', 'Labour', 'Leicester East', '@Keith_VazMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Kerry McCarthy MP', 'Labour', 'Bristol East', '@KerryMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Kevan Jones MP', 'Labour', 'North Durham', '@KevanJonesMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Kevin Brennan', 'Labour', 'Cardiff West', '@KevinBrennanMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Kwasi Kwarteng', 'Conservative', 'Spelthorne', '@kwasikwarteng')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Laura Sandys MP', 'Conservative', 'South Thanet', '@LauraSandysMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Liam Byrne', 'Labour', 'Birmingham, Hodge Hill', '@LiamByrneMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Lilian Greenwood', 'Labour', 'Nottingham South', '@LilianGreenwood')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Linda Riordan MP', 'Labour', 'Halifax', '@Linda_Riordan')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Lindsay Hoyle MP', 'Labour', 'Chorley', '@LindsayHoyle_MP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Lisa Nandy', 'Labour', 'Wigan', '@lisanandy')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Liz Kendall MP', 'Labour', 'Leicester West', '@leicesterliz')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Lorely Burt', 'Liberal Democrats', 'Solihull', '@LorelyBurt')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Louise Ellman', 'Labour', 'Liverpool, Riverside', '@LouiseEllman')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Luciana Berger', 'Labour', 'Liverpool, Wavertree', '@lucianaberger')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Lucy Powell', '', 'Manchester Central', '@LucyMPowell')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Lynne Featherstone', 'Liberal Democrats', 'Hornsey and Wood Green', '@lfeatherstone')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Malcolm Bruce', 'Liberal Democrats', 'Gordon', '@malcolmbruce')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Margaret Curran', 'Labour', 'Glasgow East', '@Margaret_Curran')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Margaret Hodge MP', 'Labour', 'Barking', '@margarethodge')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Maria Eagle MP', 'Labour', 'Liverpool, Garston', '@meaglemp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Maria_MillerMP', 'Conservative', 'Basingstoke', '@Maria_MillerMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mark Durkan', 'SDLP', 'Foyle', '@markdurkan')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mark Field MP', 'Conservative', 'Cities of London and Westminster', '@MarkFieldMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mark Garnier', 'Conservative', 'Wyre Forest', '@Mark4WyreForest')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mark Harper', 'Conservative', 'Forest of Dean', '@Mark_J_Harper')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mark Hunter', 'Liberal Democrats', 'Cheadle', '@markhuntermp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mark Lazarowicz', 'Labour', 'Edinburgh North and Leith', '@marklazarowicz')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mark Pawsey', 'Conservative', 'Rugby', '@MarkPawsey')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mark Prisk', 'Conservative', 'Hertford and Stortford', '@Mark_Prisk')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mark Pritchard', 'Conservative', 'Wrekin, The', '@MPritchardMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mark Reckless MP', 'Conservative', 'Rochester and Strood', '@MarkReckless')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mark Simmonds MP', 'Conservative', 'Boston and Skegness', '@MarkJSimmonds')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mark Williams', 'Liberal Democrats', 'Ceredigion', '@mark4ceredigion')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('MarkSpencerMP', 'Conservative', 'Sherwood', '@MarkSpencerMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Martin Horwood', 'Liberal Democrats', 'Cheltenham', '@MartinChelt')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Martin Vickers', 'Conservative', 'Cleethorpes', '@martinvickersmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mary Creagh MP', 'Labour', 'Wakefield', '@marycreagh_mp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mary Macleod', 'Conservative', 'Brentford and Isleworth', '@MaryMacleod4MP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Matthew Hancock', 'Conservative', 'West Suffolk', '@matthancockmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Matthew Offord', 'Conservative', 'Hendon', '@HendonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Meg Munn', 'Labour', 'Sheffield, Heeley', '@MegMunnMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('MegHillierMP', 'Labour', 'Hackney South and Shoreditch', '@Meg_HillierMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Menzies Campbell', 'Liberal Democrats', 'Fife North East', '@MingCampbellMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Michael Crockart', 'Liberal Democrats', 'Edinburgh West', '@CrockartMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Michael Dugher', 'Labour', 'Barnsley East', '@MichaelDugherMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Michael Ellis', 'Conservative', 'Northampton North', '@Michael_Ellis1')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Michael Fabricant', 'Conservative', 'Lichfield', '@Mike_Fabricant')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Michael McCann MP', 'Labour', 'East Kilbride, Strathaven and Lesmahagow', '@MichaelMcCannMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Michael Meacher', 'Labour', 'Oldham West and Royton', '@michaelmeacher')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Michael Moore', 'Liberal Democrats', 'Berwickshire, Roxburgh and Selkirk', '@MichaelMooreMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Michael Weir', 'SNP', 'Angus', '@mikeweirsnp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Michelle Gildernew', 'Sinn Fein', 'Fermanagh and South Tyrone', '@gildernewmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mike Freer MP', 'Conservative', 'Finchley and Golders Green', '@mikefreermp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mike Gapes MP', 'Labour', 'Ilford South', '@MikeGapes')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Mike Weatherley MP', 'Conservative', 'Hove', '@mike_weatherley')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Minister Civ Soc', 'Conservative', 'Ruislip - Northwood', '@minforcivsoc')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Nadhim Zahawi', 'Conservative', 'Stratford-on-Avon', '@nadhimzahawi')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Nadine Dorries MP', 'Conservative', 'Mid Bedfordshire', '@NadineDorriesMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Naomi Long', 'Alliance Party', 'Belfast East', '@naomi_long')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Neil Carmichael', 'Conservative', 'Stroud', '@neil_mp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Nia Griffith', 'Labour', 'Llanelli', '@NiaGriffithMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Nic Dakin MP', 'Labour', 'Scunthorpe', '@NicDakinMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Nick Clegg', 'Liberal Democrats', 'Sheffield, Hallam', '@nick_clegg')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Nick Harvey', 'Liberal Democrats', 'North Devon', '@NickHarveyND')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Nick Herbert', 'Conservative', 'Arundel and South Downs', '@nickherbertmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Nick Smith', 'Labour', 'Blaenau Gwent', '@NickSmith4BG')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Nick de Bois MP', 'Conservative', 'Enfield North', '@nickdebois')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Nicky Morgan MP', 'Conservative', 'Loughborough', '@NickyMorgan01')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Nicola Blackwood', 'Conservative', 'Oxford West and Abingdon', '@nicolablackwood')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Nigel Adams', 'Conservative', 'Selby', '@nigel4selby')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Nigel Dodds', 'DUP', 'Belfast North', '@NigelDoddsMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Norman Lamb', 'Liberal Democrats', 'North Norfolk', '@normanlamb')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Oliver Colvile MP', 'Conservative', 'Plymouth, Sutton and Devonport', '@olivercolvile')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Owen Smith MP', 'Labour', 'Pontypridd', '@OwenSmithMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Pamela Nash', 'Labour', 'Airdrie and Shotts', '@pamela_nash')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Pat Glass', 'Labour', 'North West Durham', '@PatGlassMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Pat McFadden', 'Labour', 'Wolverhampton South East', '@patmcfaddenmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Paul Blomfield', 'Labour', 'Sheffield Central', '@PaulBlomfieldMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Paul Burstow', 'Liberal Democrats', 'Sutton and Cheam', '@PaulBurstow')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Paul Flynn', 'Labour', 'Newport West', '@Paulflynnmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Paul Maskey', '', 'Belfast West', '@PaulMaskeyMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Paul Uppal', 'Conservative', 'Wolverhampton South West', '@pauluppalmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Pauline Latham MP', 'Conservative', 'Mid Derbyshire', '@Pauline_Latham')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Penny Mordaunt MP', 'Conservative', 'Portsmouth North', '@PennyMordauntMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Pete Wishart', 'SNP', 'Perth and Perthshire North', '@PeteWishart')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Peter Aldous MP', 'Conservative', 'Waveney', '@peter_aldous')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Peter Bone MP', 'Conservative', 'Wellingborough', '@PeterBoneMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Peter Hain', 'Labour', 'Neath', '@PeterHain')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Peter Luff MP', 'Conservative', 'Mid Worcestershire', '@PeterJLuff')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Phil Wilson', 'Labour', 'Sedgefield', '@PhilWilsonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Philip Davies', 'Conservative', 'Shipley', '@PhilipDaviesMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Philip Davies', 'Conservative', 'Shipley', '@PhilipDavies422')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('R. Blackman-Woods', 'Labour', 'Durham, City of', '@robertabwMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Rachel Reeves', 'Labour', 'Leeds West', '@RachelReevesMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Richard Benyon', 'Conservative', 'Newbury', '@RichardBenyonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Richard Burden MP', 'Labour', 'Birmingham, Northfield', '@RichardBurdenMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Richard Harrington', 'Conservative', 'Watford', '@Richard4Watford')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Rob Flello MP', 'Labour', 'Stoke-on-Trent South', '@RobFlelloMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Rob Wilson', 'Conservative', 'Reading East', '@RobWilson_RDG')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Robert Halfon MP', 'Conservative', 'Harlow', '@halfon4harlowMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Roger Godsiff MP', 'Labour', 'Birmingham, Sparkbrook and Small Heath', '@RogerGodsiff')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Roger Williams', 'Liberal Democrats', 'Brecon and Radnorshire', '@RogerWilliamsMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Rory Stewart', 'Conservative', 'Penrith and The Border', '@RoryStewartUK')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Rosie Cooper MP', 'Labour', 'West Lancashire', '@rosie4westlancs')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Rushanara Ali', 'Labour', 'Bethnal Green and Bow', '@rushanaraali')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Russell Brown', 'Labour', 'Dumfries and Galloway', '@russellbrownmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Sadiq Khan MP', 'Labour', 'Tooting', '@SadiqKhan')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Sam Gyimah MP', 'Conservative', 'East Surrey', '@SamGyimah')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Sarah Wollaston MP', 'Conservative', 'Totnes', '@drwollastonmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Shabana Mahmood MP', 'Labour', 'Birmingham, Ladywood', '@ShabanaMahmood')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Sharon Hodgson MP', 'Labour', 'Gateshead East and Washington West', '@SharonHodgsonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Sheila Gilmore', 'Labour', 'Edinburgh East', '@SheilaGilmoreMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Sheryll Murray MP', 'Conservative', 'South East Cornwall', '@sheryllmurray')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Simon Danczuk', 'Labour', 'Rochdale', '@SimonDanczuk')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Simon Hughes', 'Liberal Democrats', 'North Southwark and Bermondsey', '@SimonHughesMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Simon Kirby MP', 'Conservative', 'Brighton, Kemptown', '@SimonKirbyMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Simon Reevell', 'Conservative', 'Dewsbury', '@simonreevell')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Simon Wright', 'Liberal Democrats', 'Norwich South', '@SimonWrightMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Siobhain McDonagh MP', 'Labour', 'Mitcham and Morden', '@SiobhainMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Sir Tony Baldry MP', 'Conservative', 'Banbury', '@TonyBaldry')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Stephen Crabb MP', 'Conservative', 'Preseli Pembrokeshire', '@SCrabbMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Stephen Doughty', '', 'Cardiff South and Penarth', '@SDoughtyMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Stephen Gilbert', 'Liberal Democrats', 'St Austell and Newquay', '@stephen_gilbert')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Stephen Hammond MP', 'Conservative', 'Wimbledon', '@SHammondMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Stephen McPartland', 'Conservative', 'Stevenage', '@SMcPartlandMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Stephen Mosley MP', 'Conservative', 'City of Chester', '@mp4chester')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Stephen Timms', 'Labour', 'East Ham', '@stephenctimms')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Stephen Twigg', 'Labour', 'Liverpool, West Derby', '@StephenTwigg')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Stephen Williams', 'Liberal Democrats', 'Bristol West', '@swilliamsmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Steve Baker MP', 'Conservative', 'Wycombe', '@SteveBakerMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Steve Barclay', 'Conservative', 'North East Cambridgeshire', '@SteveBarclayMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Steve Brine', 'Conservative', 'Winchester', '@sbrine')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Steve McCabe', 'Labour', 'Birmingham, Hall Green', '@steve_mccabe')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Steve Rotheram', 'Labour', 'Liverpool, Walton', '@SteveRotheramMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Steve Webb', 'Liberal Democrats', 'Northavon', '@stevewebb1')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Stewart Hosie', 'SNP', 'Dundee East', '@StewartHosieMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Stewart Jackson MP', 'Conservative', 'Peterborough', '@SJacksonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Stuart Andrew MP', 'Conservative', 'Pudsey', '@StuartAndrewMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Tessa Jowell', 'Labour', 'Dulwich and West Norwood', '@jowellt')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Tessa Munt', 'Liberal Democrats', 'Wells', '@tessamunt')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Therese Coffey', 'Conservative', 'Suffolk Coastal', '@theresecoffey')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Thomas Docherty MP', 'Labour', 'Dunfermline and West Fife', '@Thomas_Docherty')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Tim Farron', 'Liberal Democrats', 'Westmorland and Lonsdale', '@timfarron')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Tim Loughton MP', 'Conservative', 'East Worthing and Shoreham', '@timloughton')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Tobias Ellwood', 'Conservative', 'Bournemouth East', '@TobiasEllwoodMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Toby Perkins MP', 'Labour', 'Chesterfield', '@tobyperkinsmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Tom Blenkinsop', 'Labour', 'Middlesbrough South and East Cleveland', '@TomBlenkinsop')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Tom Brake', 'Liberal Democrats', 'Carshalton and Wallington', '@thomasbrake')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Tom Greatrex MP', 'Labour', 'Rutherglen and Hamilton West', '@tomgreatrexmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Tom Harris', 'Labour', 'Glasgow South', '@TomHarrisMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Tracey Crouch', 'Conservative', 'Chatham and Aylesford', '@tracey_crouch')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Tristram Hunt', 'Labour', 'Stoke-on-Trent Central', '@TristramHuntMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Vernon Coaker', 'Labour', 'Gedling', '@Vernon_CoakerMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Vince Cable', 'Liberal Democrats', 'Twickenham', '@vincecable')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Virendra Sharma MP', 'Labour', 'Ealing, Southall', '@VirendraSharma')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Wayne David MP', 'Labour', 'Caerphilly', '@WayneDavidMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('William Bain', 'Labour', 'Glasgow North East', '@William_Bain')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('William Hague', 'Conservative', 'Richmond (Yorks)', '@WilliamJHague')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Yasmin Qureshi', 'Labour', 'Bolton South East', '@YasminQureshiMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Yvette Cooper', 'Labour', 'Pontefract and Castleford', '@YvetteCooperMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Yvonne Fovargue', 'Labour', 'Makerfield', '@Y_FovargueMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('Zac Goldsmith', 'Conservative', 'Richmond Park', '@ZacGoldsmith')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('andrew murrison', 'Conservative', 'Westbury', '@murrisonMP')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('angela smith mp', 'Labour', 'Penistone and Stocksbridge', '@angelasmithmp')
INSERT INTO website_mp (name, party, constituency, twitter_handle) VALUES ('caroline dinenage mp', 'Conservative', 'Gosport', '@cj_dinenage')
