INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Alabama 2','Jeff Sessions','Republican','@SenatorSessions','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Alabama 3','Richard Shelby ','Republican','@SenShelby','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Alaska  2','Mark Begich','Democratic','@SenatorBegich','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Alaska  3','Lisa Murkowski ','Republican','@lisamurkowski','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Arizona 1','Jeff Flake ','Republican','@JeffFlake','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Arizona 3','John McCain','Republican','@SenJohnMcCain','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Arkansas  2','Mark Pryor ','Democratic','@SenMarkPryor','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Arkansas  3','John Boozman ','Republican','@JohnBoozman','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('California  1','Dianne Feinstein ','Democratic','@SenFeinstein','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('California  3','Barbara Boxer','Democratic','@SenatorBoxer','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Colorado  2','Mark Udall ','Democratic','@MarkUdall','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Colorado  3','Michael Bennet ','Democratic','@SenBennetCO','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Connecticut 1','Chris Murphy ','Democratic','@ChrisMurphyCT','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Connecticut 3','Richard Blumenthal ','Democratic','@SenBlumenthal','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Delaware  1','Tom Carper ','Democratic','@SenatorCarper','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Delaware  2','Chris Coons','Democratic','@ChrisCoons','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Florida 1','Bill Nelson','Democratic','@SenBillNelson','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Florida 3','Marco Rubio','Republican','@marcorubio','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Georgia 2','Saxby Chambliss','Republican','@SaxbyChambliss','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Georgia 3','Johnny Isakson ','Republican','@SenatorIsakson','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Hawaii  1','Mazie Hirono ','Democratic','@maziehirono','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Hawaii  3','Brian Schatz ','Democratic','@brianschatz','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Idaho 2','Jim Risch','Republican','@SenatorRisch','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Idaho 3','Mike Crapo ','Republican','@MikeCrapo','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Illinois  2','Dick Durbin','Democratic','@SenatorDurbin','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Illinois  3','Mark Kirk','Republican','@SenatorKirk','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Indiana 1','Joe Donnelly ','Democratic','@SenDonnelly','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Indiana 3','Dan Coats','Republican','@SenDanCoats','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Iowa  2','Tom Harkin ','Democratic','@SenatorHarkin','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Iowa  3','Chuck Grassley ','Republican','@ChuckGrassley','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Kansas  2','Pat Roberts','Republican','@SenPatRoberts','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Kansas  3','Jerry Moran','Republican','@JerryMoran','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Kentucky  2','Mitch McConnell','Republican','@McConnellPress','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Kentucky  3','Rand Paul','Republican','@SenRandPaul','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Louisiana 2','Mary Landrieu','Democratic','@SenLandrieu','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Louisiana 3','David Vitter ','Republican','@senatorvitter','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Maine 1','Angus King ','Independent','@SenAngusKing','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Maine 2','Susan Collins','Republican','@SenatorCollins','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Maryland  1','Ben Cardin ','Democratic','@SenatorCardin','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Maryland  3','Barbara Mikulski ','Democratic','@SenatorBarb','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Massachusetts 1','Elizabeth Warren ','Democratic','@SenWarren','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Massachusetts 2','Ed Markey','Democratic','@MarkeyMemo','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Michigan  1','Debbie Stabenow','Democratic','@stabenow','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Michigan  2','Carl Levin ','Democratic','@SenCarlLevin','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Minnesota 1','Amy Klobuchar','Democratic-Farmer-Labor','@amyklobuchar','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Minnesota 2','Al Franken ','Democratic-Farmer-Labor','@alfranken','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Mississippi 1','Roger Wicker ','Republican','@SenatorWicker','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Mississippi 2','Thad Cochran ','Republican','@SenThadCochran','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Missouri  1','Claire McCaskill ','Democratic','@clairecmc','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Missouri  3','Roy Blunt','Republican','@RoyBlunt','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Montana 1','Jon Tester ','Democratic','@jontester','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Montana 2','John Walsh ','Democratic','@JohnWalsh','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Nebraska  1','Deb Fischer','Republican','@SenatorFischer','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Nebraska  2','Mike Johanns ','Republican','@Mike_Johanns','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Nevada  1','Dean Heller','Republican','@SenDeanHeller','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Nevada  3','Harry Reid ','Democratic','@SenatorReid','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('New Hampshire 2','Jeanne Shaheen ','Democratic','@SenatorShaheen','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('New Hampshire 3','Kelly Ayotte ','Republican','@KellyAyotte','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('New Jersey  1','Bob Menendez ','Democratic','@SenatorMenendez','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('New Jersey  2','Cory Booker','Democratic','@CoryBooker','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('New Mexico  1','Martin Heinrich','Democratic','@MartinHeinrich','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('New Mexico  2','Tom Udall','Democratic','@SenatorTomUdall','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('New York  1','Kirsten Gillibrand ','Democratic','@SenGillibrand','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('New York  3','Chuck Schumer','Democratic','@SenSchumer','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('North Carolina  2','Kay Hagan','Democratic','@SenatorHagan','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('North Carolina  3','Richard Burr ','Republican','@SenatorBurr','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('North Dakota  1','Heidi Heitkamp ','Democratic','@SenatorHeitkamp','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('North Dakota  3','John Hoeven','Republican','@SenJohnHoeven','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Ohio  1','Sherrod Brown','Democratic','@SenSherrodBrown','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Ohio  3','Rob Portman','Republican','@robportman','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Oklahoma  2','Jim Inhofe ','Republican','@jiminhofe','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Oklahoma  3','Tom Coburn ','Republican','@TomCoburn','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Oregon  2','Jeff Merkley ','Democratic','@SenJeffMerkley','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Oregon  3','Ron Wyden','Democratic','@RonWyden','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Pennsylvania  1','Bob Casey, Jr. ','Democratic','@SenBobCasey','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Pennsylvania  3','Pat Toomey ','Republican','@SenToomey','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Rhode Island  1','Sheldon Whitehouse ','Democratic','@SenWhitehouse','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Rhode Island  2','Jack Reed','Democratic','@SenJackReed','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('South Carolina  2','Lindsey Graham ','Republican','@GrahamBlog','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('South Carolina  3','Tim Scott','Republican','@SenatorTimScott','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('South Dakota  2','Tim Johnson','Democratic','@SenJohnsonSD','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('South Dakota  3','John Thune ','Republican','@SenJohnThune','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Tennessee 1','Bob Corker ','Republican','@SenBobCorker','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Tennessee 2','Lamar Alexander','Republican','@SenAlexander','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Texas 1','Ted Cruz ','Republican','@SenTedCruz','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Texas 2','John Cornyn','Republican','@JohnCornyn','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Utah  1','Orrin Hatch','Republican','@SenOrrinHatch','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Utah  3','Mike Lee ','Republican','@SenMikeLee','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Vermont 1','Bernie Sanders ','Independent(Democratic Socialist)','@SenSanders','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Vermont 3','Patrick Leahy','Democratic','@SenatorLeahy','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Virginia  1','Tim Kaine','Democratic','@timkaine','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Virginia  2','Mark Warner','Democratic','@MarkWarner','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Washington  1','Maria Cantwell ','Democratic','@CantwellPress','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Washington  3','Patty Murray ','Democratic','@PattyMurray','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('West Virginia 1','Joe Manchin','Democratic','@Sen_JoeManchin','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('West Virginia 2','Jay Rockefeller','Democratic','@SenRockefeller','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Wisconsin 1','Tammy Baldwin','Democratic','@SenatorBaldwin','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Wisconsin 3','Ron Johnson','Republican','@SenRonJohnson','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Wyoming 1','John Barrasso','Republican','@SenJohnBarrasso','US');
INSERT INTO website_politico (constituency, name, party, twitter_handle, type) VALUES ('Wyoming 2','Mike Enzi','Republican','@SenatorEnzi','US');